config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: "supports#index"

  resources :supports, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
    resources :orders, only:[:index,:create]
    resources :comments, only:[:create, :destroy]
  end
end

app/models/support.rb
class Support < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :item
    validates :price
    validates :reason
    validates :status
  end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @supports = Support.all.order('created_at DESC')
  end

  def new
    @support = Support.new
  end

  def create
    @support = Support.new(support_params)
    if @support.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @support = Support.find(params[:id])
    @total = @support.orders.sum(:price)
    @comment = Comment.new
    @comments = @support.comments.order(created_at: :desc)
  end

  def edit
    @support = Support.find(params[:id])
  end

  def update
    @support = Support.find(params[:id])
    if @support.update(support_params)
      redirect_to support_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @support = Support.find(params[:id])
    @support.destroy
    redirect_to root_path
  end

  private

  def support_params
    params.require(:support).permit(:item, :price, :reason, :status, :image).merge(user_id: current_user.id)
  end
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/supports/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/supports/_support.html.erb
<%= link_to support_path(support) do %>   
  <div class="support">
    <div class="upper-support">
      <div class="support-user">
        <%= support.user.last_name + support.user.first_name %>
      </div>
      <div class="support-date">
        <%= support.created_at %>
      </div>
    </div>
    <div class="lower-supports">
      <div class="support-content">
        <%= support.item %>
      </div>
    </div>
  </div>
<% end %>

app/views/supports/edit.html.erb
<div class = "content">
  <%= form_with model: @support, class: 'form', local: true do |f| %>
    <%= render 'error_messages', model: f.object %>
  
    <div class="support-form">
      <div class="each-form">
        <div class="weight-bold-text">
          欲しいもの
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :item, class:"supports-text", id:"support-name", placeholder:"例(学習机、塾代三ヶ月、本)", maxlength:"40" %>
      </div>

      <div class="each-form">
        <div class="weight-bold-text">
          金額(¥)
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :price, class:"supports-text", id:"support-price", placeholder:"例）300" %>
      </div>

      <div class="each-form">
        <div class="weight-bold-text">
          なぜ欲しいか説明してください
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :reason, class:"supports-text", id:"support-info", placeholder:"例)私は、将来医者になりたいです。そのためにいっぱい勉強する必要があります。しかし、母子家庭のため欲しい本が買えないので困っています" ,rows:"7" ,maxlength:"1000" %>
      </div>

      <div class="each-form">
        <div class="weight-bold-text">
          あなたのことについて教えてください
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :status, class:"supports-text", id:"support-info", placeholder:"例)私は今、中学３年生でこれから受験です。
        母子家庭で、あまり裕福ではありません。塾に通うお金もないのでせめていい参考書を使いたいです。" ,rows:"7" ,maxlength:"1000" %>
      </div>

      <div class="each-form">
        <div class="weight-bold-text">
          画像
          <span class="indispensable">任意</span>
        </div>
        <div class="cdivck-upload">
          <p>
            あなたの顔写真、もしくは、何か見せたい画像があれば載せて下さい
          </p>
          <%= f.file_field :image, id:"support-image" %>
        </div>
        <div id="image-list" class="image-list"></div>
      </div>
    </div>
    <%= f.submit '送信', class: 'form-submit' %>
  <% end %>
  
  <%= link_to support_path(@support), class: "donate-back" do %>
    <div class = "donate-string">戻る</div>
  <% end %>

  <%= link_to "削除",support_path(@support), method: :delete, class:"support-destroy" %>

</div>

app/views/supports/index.html.erb
<div class="content">
  <div class="picture">
    <%= image_tag "phonto.jpg", class:"pic" %>
  </div>
  <div class="a">
     
  </div>
  <div class="attention">
  ※ 枠線内をクリックすることで詳細ページに移動します<br/>
  ※ 詳細ページにて寄付ができます
  </div>
  
  <div class="supports">
    <ul class='support-lists'>
      <% @supports.each do |support| %>
        <li class='list'>
          <%= link_to support_path(support) do %>   
            <div class="support">
              <div class = "support-pic">
                <% if support.image.present? %>
                  <%= image_tag support.image, class:"pictures" %>
                <% else %>
                  <%= image_tag "46477.jpg", class:"pictures" %>
                <% end %>
              </div>
              <div class="support-user">
                <div class = "title">お名前</div>
                <div class="support-content"><%= support.user.last_name + support.user.first_name %> さん</div>
              </div>
              <div class="support-date">
                <div class = "title">登録日</div>
                <div class="support-content"><%= support.created_at.strftime('%Y/%m/%d')  %></div>
              </div>
              <div class="support-item">
                <div class = "title">欲しいもの</div>
                <div class="support-content"><%= support.item %></div>
              </div>
              <div class="support-reason">
                <div class = "title">欲しい理由</div>
                <div class="support-content"><%= support.reason %></div>
              </div>
            </div>
          <% end %> 
        </li>
      <% end %> 
    </ul>
  </div> 
</div>


<div class="">
  </div>
  <div class="">
  </div>

app/views/supports/new.html.erb
<div class = "content">
  <%= form_with model: @support, class: 'form', local: true do |f| %>
    <%= render 'error_messages', model: f.object %>
  
    <div class="support-form">
      <div class="each-form">
        <div class="weight-bold-text">
          欲しいもの
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :item, class:"supports-text", id:"support-name", placeholder:"例(学習机、塾代三ヶ月、本)", maxlength:"40" %>
      </div>

      <div class="each-form">
        <div class="weight-bold-text">
          金額(¥)
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :price, class:"supports-text", id:"support-price", placeholder:"例）300" %>
      </div>

      <div class="each-form">
        <div class="weight-bold-text">
          なぜ欲しいか説明<br>
          してください
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :reason, class:"supports-text", id:"support-info", placeholder:"例)私は、将来医者になりたいです。そのためにいっぱい勉強する必要があります。しかし、母子家庭のため欲しい本が買えないので困っています" ,rows:"7" ,maxlength:"1000" %>
      </div>

      <div class="each-form">
        <div class="weight-bold-text">
          あなたのことについて<br>教えてください
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :status, class:"supports-text", id:"support-info", placeholder:"例)私は今、中学３年生でこれから受験です。母子家庭で、あまり裕福ではありません。塾に通うお金もないのでせめていい参考書を使いたいです。" ,rows:"7" ,maxlength:"1000" %>
      </div>

      <div class="each-form">
        <div class="weight-bold-text">
          画像
          <span class="indispensable">任意</span>
        </div>
        <div class="cdivck-upload">
          <p>
            あなたの顔写真、もしくは、何か見せたい画像があれば載せて下さい
          </p>
          <%= f.file_field :image, id:"support-image" %>
        </div>
        <div id="image-list" class="image-list"></div>
      </div>
    </div>
    <%= f.submit '送信', class: 'form-submit' %>
  <% end %>

  <%= link_to root_path, class: "donate" do %>
    <div class = "donate-string">戻る</div>
  <% end %>
</div>

app/views/supports/show.html.erb
<div class="content">
  <div class="support-up" >
    <div class="show-pic">
      <% if @support.image.attached? %>
        <%= image_tag @support.image, class:"show-picture" %>
      <% else %>
        <%= image_tag "46477.jpg", class:"show-default" %>
      <% end %>
    </div>
    <div class ="show-right">
      <div class="support-user">
        <div class = "title">お名前</div>
        <div class="support-content-show"><%= @support.user.last_name + @support.user.first_name %> さん</div>
      </div>
      <div class="support-date">
        <div class = "title">登録日</div>
        <div class="support-content-show"><%= @support.created_at.strftime('%Y/%m/%d')  %></div>
      </div>
      <div class="support-item">
        <div class = "title">欲しいもの</div>
        <div class="support-content-show"><%= @support.item %></div>
      </div>
      <div class="support-item">
        <div class = "title">目標金額</div>
        <div class="support-content-show"><%= @support.price %></div>
      </div>
      <div class="support-item">
        <div class = "title">これまでの支援金額</div>
        <div class="support-content-show"><%= @total %></div>
      </div>
    </div>
  </div>

  <div class="support-down">
    <div class="support-reason">
      <div class = "title">欲しい理由</div>
      <div class="support-content"><%= @support.reason %></div>
    </div>

    <div class="support-status">
      <div class = "title">今の現状</div>
      <div class="support-content"><%= @support.status %></div>
    </div>
  </div>

  <%= link_to support_orders_path(@support), class: "donate" do %>
    <div class = "donate-string">寄付</div>
  <% end %>
  <div class = "a" ></div>
  <div class="container">
    <p class = "donate-attention">もし、<%= @support.user.last_name%>さんが役立つ情報があれば共有しましょう</p>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments.present? %>
        <div id="list">
        </div>
        <% @comments.each do |comment|  %>
          <div class = "comment" data-id =<%= comment.support.id %> id="comment">
            <div id= ”comment-name” ><%= comment.user.last_name %>さん：</div>
            <div ><%= comment.content %></div>
          </div>
        <% end %>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <%= form_with model: [@support, @comment], local: true ,id: "form" do |form|  %>
        <div class = "comment-push">
          <%= form.text_area :content, placeholder: "コメントする", rows: "2",class: "comment-form", id: "content"%>
          <%= form.submit "コメントする" ,class: "comment-submit", id: "submit"%>
        </div>
      <% end %>

      <%= link_to root_path, class: "donate-back" do %>
        <div class = "donate-string">戻る</div>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>


    <% if user_signed_in?  %>
      <% if  current_user.id == @support.user_id%>
        <%= link_to "編集", edit_support_path(@support), method: :get, class: "edit-btn" %>
      <% end %>
    <% end %>

  </div>

  <div><br/><br/><br/><br/></div>
</div>
  