config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: "supports#index"

  resources :supports, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
    resources :orders, only:[:index,:create]
    resources :comments, only:[:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonateApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <link href="https://fonts.googleapis.com/css?family=Caveat rel= "stylesheet">

    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application'  %>
  </head>

  <body>
    <header>
      <nav class="gnav" class="fixed">
        <div class = "site-name">
          <%= link_to root_path do%>
            <p class = "name">Donate App</p>
          <% end %>
        </div>
        <div class = "header-right">
          <ul class="gnav-list">
            <!--<li class="gnav-item"> <%=link_to "活動内容", "#" ,class: "gnav-link"%> </li>
            <li class="gnav-item"> <%=link_to "慈善団体に寄付","#",class: "gnav-link"%></li>-->
            <li class="gnav-item"> <%=link_to "支援の申し込み", new_support_path,class: "gnav-link"%></li>
            <% if user_signed_in?%>
              <li class="gnav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "gnav-link"%></li>
            <% else %>
              <li class="gnav-item"><%=link_to "アカウントの作成",new_user_registration_path, class: "gnav-link"%></li>
              <li class="gnav-item"> <%=link_to "ログイン",new_user_session_path, class: "gnav-link"%></li>
            <%end%>
          </ul>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>